package com.hertzds.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import com.hertzds.data.prefs.AppLanguage
import java.util.Locale

/**
 * All user-facing copy, in one place, in both languages. The app never restarts
 * to switch language — [LocalStrings] recomposes instantly when the setting
 * changes, since nothing here touches Android string resources or configuration.
 */
data class Strings(
    // Empty state / hero
    val heroTitle: String,
    val heroSubtitle: String,
    val suggestion1Prompt: String,
    val suggestion1Hint: String,
    val suggestion2Prompt: String,
    val suggestion2Hint: String,
    val suggestion3Prompt: String,
    val suggestion3Hint: String,
    val disclaimer: String,
    val working: String,
    val micPermissionRequired: String,
    val lowCreditsPrefix: String,
    val lowCreditsSuffix: String,

    // Composer
    val askAnything: String,
    val send: String,
    val stop: String,
    val newChat: String,
    val ghostOn: String,
    val ghostOff: String,
    val mute: String,
    val unmute: String,
    val pause: String,
    val resume: String,
    val end: String,
    val dictate: String,
    val call: String,

    // Drawer
    val newGhostChat: String,
    val conversations: String,
    val credits: String,
    val manage: String,
    val dateToday: String,
    val dateYesterday: String,
    val date7Days: String,
    val date30Days: String,
    val dateOlder: String,

    // Dialogs
    val cancel: String,
    val create: String,
    val save: String,
    val close: String,
    val nameOptional: String,
    val systemPromptOptional: String,
    val model: String,
    val modelProDesc: String,
    val modelVisionDesc: String,
    val modelFlashDesc: String,
    val renameChat: String,
    val name: String,

    // Message row
    val insideHead: String,
    val error: String,
    val cancelled: String,
    val copy: String,
    val copied: String,
    val readAloud: String,
    val stopReading: String,

    // Settings — root
    val settings: String,
    val keysAndCredits: String,
    val keysAndCreditsSubtitle: String,
    val aiBehavior: String,
    val aiBehaviorSubtitle: String,
    val voice: String,
    val voiceSubtitle: String,
    val about: String,
    val aboutSubtitle: String,
    val language: String,
    val languageSystem: String,
    val languageCzech: String,
    val languageEnglish: String,

    // Settings — keys
    val manageKeysDesc: String,
    val manageKeys: String,
    val manageMemory: String,

    // Settings — AI behavior
    val defaultModel: String,
    val creativity: String,
    val maxToolIterations: String,
    val autoNameChats: String,
    val autoNameChatsDesc: String,
    val webSearch: String,
    val fileTools: String,
    val longTermMemory: String,
    val systemPrompt: String,
    val edit: String,

    // Settings — voice
    val streamSpeech: String,
    val textToSpeech: String,
    val speechToText: String,
    val systemEngine: String,
    val piperOffline: String,
    val whisperOffline: String,
    val speechSpeed: String,
    val voiceModesHint: String,
    val downloaded: String,
    val notDownloaded: String,
    val active: String,
    val select: String,
    val download: String,
    val sileroVad: String,
    val sileroVadDownloaded: String,
    val sileroVadHint: String,
    val downloadError: String,

    // Settings — about
    val version: String,
    val checkForUpdates: String,
    val upToDate: String,
    val updateAvailable: String,
    val visitWebsite: String,
    val legalDocuments: String,
    val openSourceNotice: String,

    // Keys screen
    val closeAction: String,
    val refresh: String,
    val totalAvailable: String,
    val keyChainHint: String,
    val spent: String,
    val percentRemaining: String,
    val topUp: String,
    val deleteKey: String,
    val cooldownNotice: String,
    val noKeys: String,
    val addKey: String,
    val addDeepSeekKey: String,
    val keyLabel: String,
    val nameOptionalUpper: String,
    val keyEncryptedNotice: String,
    val duplicateKeyError: String,
    val manualTopUpTitle: String,
    val manualTopUpHint: String,
    val amountUsd: String,
    val clear: String,

    // Memory screen
    val agentMemory: String,
    val newMemory: String,
    val noMemoriesYet: String,
    val noMemoriesHint: String,
    val pin: String,
    val editMemory: String,
    val title: String,
    val content: String,

    // Tasks screen
    val scheduledTasks: String,
    val noTasks: String,
    val noTasksHint: String,
    val everyMinutesNext: String,

    // EULA
    val welcomeTitle: String,
    val welcomeBody: String,
    val agree: String,
    val exit: String,
) {
    companion object {
        val EN = Strings(
            heroTitle = "Ready when you are.",
            heroSubtitle = "Agent with web, files and memory.\nAnswers are read aloud and it works in background.",
            suggestion1Prompt = "What's in the international press today?",
            suggestion1Hint = "I'll search and summarize.",
            suggestion2Prompt = "Remember: my Wi-Fi password is hertz2026",
            suggestion2Hint = "Saved to long-term memory.",
            suggestion3Prompt = "Every day at 8:00 summarize the weather",
            suggestion3Hint = "Schedules a recurring task.",
            disclaimer = "Hertz-DS can make mistakes — just like people.",
            working = "Working",
            micPermissionRequired = "Microphone permission is required.",
            lowCreditsPrefix = "Low credits: ",
            lowCreditsSuffix = "$ remaining",
            askAnything = "Ask anything…",
            send = "Send",
            stop = "Stop",
            newChat = "New chat",
            ghostOn = "Ghost on",
            ghostOff = "Ghost off",
            mute = "Mute",
            unmute = "Unmute",
            pause = "Pause",
            resume = "Resume",
            end = "End",
            dictate = "Dictate",
            call = "Call",
            newGhostChat = "New ghost chat",
            conversations = "CONVERSATIONS",
            credits = "CREDITS",
            manage = "Manage",
            dateToday = "Today",
            dateYesterday = "Yesterday",
            date7Days = "Previous 7 days",
            date30Days = "Previous 30 days",
            dateOlder = "Older",
            cancel = "Cancel",
            create = "Create",
            save = "Save",
            close = "Close",
            nameOptional = "Name (optional)",
            systemPromptOptional = "System prompt (optional)",
            model = "Model",
            modelProDesc = "Most accurate · higher price",
            modelVisionDesc = "Understands images",
            modelFlashDesc = "Fast · cheapest",
            renameChat = "Rename chat",
            name = "Name",
            insideHead = "inside head",
            error = "error",
            cancelled = "cancelled",
            copy = "Copy",
            copied = "Copied",
            readAloud = "Read aloud",
            stopReading = "Stop",
            settings = "Settings",
            keysAndCredits = "Keys & Credits",
            keysAndCreditsSubtitle = "API keys, balance and billing",
            aiBehavior = "AI Behavior",
            aiBehaviorSubtitle = "Model, system prompt and tools",
            voice = "Voice",
            voiceSubtitle = "TTS, STT and speech",
            about = "About",
            aboutSubtitle = "Updates, links and legal",
            language = "Language",
            languageSystem = "System",
            languageCzech = "Čeština",
            languageEnglish = "English",
            manageKeysDesc = "Manage your DeepSeek API keys and check remaining credits.",
            manageKeys = "Manage keys",
            manageMemory = "Manage memory",
            defaultModel = "Default model",
            creativity = "Creativity",
            maxToolIterations = "Max tool iterations",
            autoNameChats = "Auto-name chats",
            autoNameChatsDesc = "Always on — new chats are titled automatically",
            webSearch = "Web search",
            fileTools = "File tools",
            longTermMemory = "Long-term memory",
            systemPrompt = "SYSTEM PROMPT",
            edit = "Edit",
            streamSpeech = "Stream speech sentence-by-sentence",
            textToSpeech = "Text-to-speech",
            speechToText = "Speech recognition",
            systemEngine = "System",
            piperOffline = "Piper · offline",
            whisperOffline = "Whisper · offline",
            speechSpeed = "Speech speed",
            voiceModesHint = "Dictation and Call mode buttons appear in the composer when the field is empty. No default hands-free toggle.",
            downloaded = "downloaded",
            notDownloaded = "not downloaded",
            active = "Active ✓",
            select = "Select",
            download = "Download",
            sileroVad = "Silero VAD",
            sileroVadDownloaded = "downloaded ✓",
            sileroVadHint = "recommended for call mode · ~2 MB",
            downloadError = "Error",
            version = "Version",
            checkForUpdates = "Check for updates",
            upToDate = "You're up to date",
            updateAvailable = "Update available",
            visitWebsite = "kuclab.org — visit our website",
            legalDocuments = "Legal documents & Privacy Policy",
            openSourceNotice = "Hertz-DS is open source (MIT). All data stays on-device except model requests to api.deepseek.com.",
            closeAction = "Close",
            refresh = "Refresh",
            totalAvailable = "TOTAL AVAILABLE",
            keyChainHint = "Keys chain: when one runs out (401/402/429), the agent moves to the next.",
            spent = "spent",
            percentRemaining = "%% remaining",
            topUp = "Top up…",
            deleteKey = "Delete key",
            cooldownNotice = "⏸ in cooldown after an API error",
            noKeys = "No keys yet. Grab one at platform.deepseek.com —\nthe agent can't start without it.",
            addKey = "Add key",
            addDeepSeekKey = "Add DeepSeek key",
            keyLabel = "KEY",
            nameOptionalUpper = "NAME (OPTIONAL)",
            keyEncryptedNotice = "The key is encrypted with the Android Keystore; the plaintext is never stored.",
            duplicateKeyError = "This key is already saved.",
            manualTopUpTitle = "Manual top-up",
            manualTopUpHint = "How many $ does this key hold in total? The app subtracts local usage when DeepSeek doesn't report a balance.",
            amountUsd = "Amount in USD",
            clear = "Clear",
            agentMemory = "Agent memory",
            newMemory = "New memory",
            noMemoriesYet = "The agent doesn't remember anything yet",
            noMemoriesHint = "It saves facts on its own via the remember tool.\nOr add one manually with the + button.",
            pin = "PIN",
            editMemory = "Edit",
            title = "Title",
            content = "Content…",
            scheduledTasks = "Scheduled tasks",
            noTasks = "No tasks",
            noTasksHint = "Tell the agent: \"summarize the news for me every morning at 7:30\" —\nit schedules itself via the schedule_task tool.",
            everyMinutesNext = "every %d min · next %s",
            welcomeTitle = "Welcome to Hertz-DS",
            welcomeBody = "Local agentic assistant powered by DeepSeek.\n\n" +
                "• All data (chats, memory, files, keys) stays on this device only.\n" +
                "• No account, no telemetry, no cloud.\n" +
                "• Requests go directly to api.deepseek.com under your own API key\n" +
                "  and are billed from your credits.\n" +
                "• Agent tools may access the internet and the app's workspace folder.\n\n" +
                "By continuing you agree to this processing model.",
            agree = "Agree",
            exit = "Exit",
        )

        val CS = Strings(
            heroTitle = "Připraven, kdykoliv budeš chtít.",
            heroSubtitle = "Agent s přístupem na web, k souborům a s pamětí.\nOdpovědi čte nahlas a pracuje i na pozadí.",
            suggestion1Prompt = "Co je dnes v mezinárodním tisku?",
            suggestion1Hint = "Vyhledám a shrnu to.",
            suggestion2Prompt = "Zapamatuj si: heslo na Wi-Fi je hertz2026",
            suggestion2Hint = "Uloženo do dlouhodobé paměti.",
            suggestion3Prompt = "Každý den v 8:00 mi shrň počasí",
            suggestion3Hint = "Naplánuje opakovanou úlohu.",
            disclaimer = "Hertz-DS se může mýlit — stejně jako lidé.",
            working = "Pracuji",
            micPermissionRequired = "Je vyžadováno oprávnění k mikrofonu.",
            lowCreditsPrefix = "Nízký kredit: zbývá ",
            lowCreditsSuffix = "$",
            askAnything = "Zeptej se na cokoliv…",
            send = "Odeslat",
            stop = "Zastavit",
            newChat = "Nový chat",
            ghostOn = "Ghost zapnut",
            ghostOff = "Ghost vypnut",
            mute = "Ztlumit",
            unmute = "Zrušit ztlumení",
            pause = "Pauza",
            resume = "Pokračovat",
            end = "Ukončit",
            dictate = "Nahrávat",
            call = "Volat",
            newGhostChat = "Nový ghost chat",
            conversations = "KONVERZACE",
            credits = "KREDITY",
            manage = "Spravovat",
            dateToday = "Dnes",
            dateYesterday = "Včera",
            date7Days = "Posledních 7 dní",
            date30Days = "Posledních 30 dní",
            dateOlder = "Starší",
            cancel = "Zrušit",
            create = "Vytvořit",
            save = "Uložit",
            close = "Zavřít",
            nameOptional = "Název (volitelné)",
            systemPromptOptional = "Systémový prompt (volitelné)",
            model = "Model",
            modelProDesc = "Nejpřesnější · vyšší cena",
            modelVisionDesc = "Rozumí obrázkům",
            modelFlashDesc = "Rychlý · nejlevnější",
            renameChat = "Přejmenovat chat",
            name = "Název",
            insideHead = "v hlavě",
            error = "chyba",
            cancelled = "zrušeno",
            copy = "Kopírovat",
            copied = "Zkopírováno",
            readAloud = "Přečíst",
            stopReading = "Zastavit",
            settings = "Nastavení",
            keysAndCredits = "Klíče a kredity",
            keysAndCreditsSubtitle = "API klíče, zůstatek a fakturace",
            aiBehavior = "Chování AI",
            aiBehaviorSubtitle = "Model, systémový prompt a nástroje",
            voice = "Hlas",
            voiceSubtitle = "TTS, STT a řeč",
            about = "O aplikaci",
            aboutSubtitle = "Aktualizace, odkazy a právní informace",
            language = "Jazyk",
            languageSystem = "Systémový",
            languageCzech = "Čeština",
            languageEnglish = "English",
            manageKeysDesc = "Spravuj své DeepSeek API klíče a sleduj zbývající kredit.",
            manageKeys = "Spravovat klíče",
            manageMemory = "Spravovat paměť",
            defaultModel = "Výchozí model",
            creativity = "Kreativita",
            maxToolIterations = "Max. iterací nástrojů",
            autoNameChats = "Automatické pojmenování chatů",
            autoNameChatsDesc = "Vždy zapnuto — nové chaty se pojmenují automaticky",
            webSearch = "Vyhledávání na webu",
            fileTools = "Práce se soubory",
            longTermMemory = "Dlouhodobá paměť",
            systemPrompt = "SYSTÉMOVÝ PROMPT",
            edit = "Upravit",
            streamSpeech = "Číst řeč po větách, jak vzniká",
            textToSpeech = "Převod textu na řeč",
            speechToText = "Rozpoznávání řeči",
            systemEngine = "Systémový",
            piperOffline = "Piper · offline",
            whisperOffline = "Whisper · offline",
            speechSpeed = "Rychlost řeči",
            voiceModesHint = "Tlačítka pro nahrávání a call mode se objeví v poli pro psaní, když je prázdné. Žádný výchozí handsfree přepínač.",
            downloaded = "staženo",
            notDownloaded = "nestaženo",
            active = "Aktivní ✓",
            select = "Vybrat",
            download = "Stáhnout",
            sileroVad = "Silero VAD",
            sileroVadDownloaded = "staženo ✓",
            sileroVadHint = "doporučeno pro call mode · ~2 MB",
            downloadError = "Chyba",
            version = "Verze",
            checkForUpdates = "Zkontrolovat aktualizace",
            upToDate = "Máš nejnovější verzi",
            updateAvailable = "Dostupná aktualizace",
            visitWebsite = "kuclab.org — navštiv náš web",
            legalDocuments = "Právní dokumenty a ochrana soukromí",
            openSourceNotice = "Hertz-DS je open source (MIT). Všechna data zůstávají v zařízení kromě požadavků na model na api.deepseek.com.",
            closeAction = "Zavřít",
            refresh = "Obnovit",
            totalAvailable = "CELKEM K DISPOZICI",
            keyChainHint = "Klíče se řetězí: když jeden dojde (401/402/429), agent přejde na další.",
            spent = "utraceno",
            percentRemaining = "%% zbývá",
            topUp = "Dobít…",
            deleteKey = "Smazat klíč",
            cooldownNotice = "⏸ v cooldownu po chybě API",
            noKeys = "Žádné klíče. Vezmi klíč z platform.deepseek.com —\nbez něj agent nemůže startovat.",
            addKey = "Přidat klíč",
            addDeepSeekKey = "Přidat DeepSeek klíč",
            keyLabel = "KLÍČ",
            nameOptionalUpper = "NÁZEV (VOLITELNÉ)",
            keyEncryptedNotice = "Klíč je šifrovaný přes Android Keystore; plaintext nikdy neuložíme.",
            duplicateKeyError = "Tento klíč už je uložený.",
            manualTopUpTitle = "Manuální dobití",
            manualTopUpHint = "Kolik $ má klíč celkem? Aplikace odečítá lokální spotřebu, když se nedozví zůstatek od DeepSeek.",
            amountUsd = "Částka v USD",
            clear = "Vymazat",
            agentMemory = "Paměť agenta",
            newMemory = "Nová vzpomínka",
            noMemoriesYet = "Agent si zatím nic nepamatuje",
            noMemoriesHint = "Sám si ukládá fakta přes nástroj remember.\nNebo je přidej ručně tlačítkem +.",
            pin = "PIN",
            editMemory = "Upravit",
            title = "Nadpis",
            content = "Obsah…",
            scheduledTasks = "Naplánované úlohy",
            noTasks = "Žádné úlohy",
            noTasksHint = "Řekni agentovi: „každé ráno v 7:30 mi shrň novinky“ —\nsám se naplánuje přes nástroj schedule_task.",
            everyMinutesNext = "každých %d min · příští %s",
            welcomeTitle = "Vítej v Hertz-DS",
            welcomeBody = "Lokální agentní asistent poháněný DeepSeek.\n\n" +
                "• Všechna data (chaty, paměť, soubory, klíče) zůstávají pouze v tomto zařízení.\n" +
                "• Žádný účet, žádná telemetrie, žádný cloud.\n" +
                "• Požadavky jdou přímo na api.deepseek.com pod tvým vlastním API klíčem\n" +
                "  a jsou účtovány z tvého kreditu.\n" +
                "• Nástroje agenta mohou přistupovat k internetu a pracovní složce aplikace.\n\n" +
                "Pokračováním souhlasíš s tímto způsobem zpracování.",
            agree = "Souhlasím",
            exit = "Ukončit",
        )

        /** Resolves SYSTEM to the device locale, defaulting to English. */
        fun resolve(language: AppLanguage): Strings = when (language) {
            AppLanguage.CZECH -> CS
            AppLanguage.ENGLISH -> EN
            AppLanguage.SYSTEM -> if (Locale.getDefault().language == "cs") CS else EN
        }
    }
}

val LocalStrings = staticCompositionLocalOf { Strings.EN }
